version: '3.3'
services:
  mongo:
    image: 'mongo:3.4.1'
    ports:
    - '27017:27017'
    volumes:
    - 'mongo:/data/db'
  icompass:
    tty: true
    stdin_open: true
    depends_on:
    - 'mongo'
    build:
      context: ../
#      cache_from:
#      - olinfse/goober:latest
    command: node icompass.js
    ports:
    - '8080:8080'
volumes:
  mongo:
