#!/usr/bin/env bash
set -euo pipefail
. "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"

"$IC_ROOT/node_modules/.bin/webpack" --config "$IC_ROOT/config/webpack/vendor.js"
"$IC_ROOT/node_modules/.bin/webpack" --config "$IC_ROOT/config/webpack/prod.js"
