#!/usr/bin/env bash
set -euo pipefail
. "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"
ensure_credentials_exist

. "$IC_ROOT/build/credentials/runner.sh"

# Any update to this file should be made to ./deploy-staging too
scp -i "$pem_file" "$IC_ROOT/build/credentials/prod.env" "$EC2_INSTANCE:~/prod.env"
scp -i "$pem_file" "$IC_ROOT/config/docker/compose.yml" "$EC2_INSTANCE:~/compose.yml"

ssh -i "$pem_file" "$EC2_INSTANCE" << 'ENDSSH'
sudo docker pull thecardkid/icompass:latest
sudo `which docker-compose` -f compose.yml down
sudo `which docker-compose` -f compose.yml up -d
sudo docker ps
ENDSSH
