#!/usr/bin/env bash
set -euo pipefail
. "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"
ensure_credentials_exist

. "$IC_ROOT/build/credentials/runner.sh"

# Any update to this file should be made to ./deploy-staging too
scp -i "$pem_file" "$IC_ROOT/build/credentials/prod.env" "$EC2_INSTANCE:~/prod.env"

ssh -i "$pem_file" "$EC2_INSTANCE" << 'ENDSSH'
sudo docker pull thecardkid/icompass:latest
sudo docker container kill production
sudo docker system prune --force
sudo docker run -p 8080:8080 --name production --env-file prod.env --detach thecardkid/icompass:latest
ENDSSH
