#!/usr/bin/env bash
set -euo pipefail
. "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"
ensure_credentials_exist

. "$IC_ROOT/build/credentials/runner.sh"

# These are commands documented after running on an Amazon Linux instance; the
# script has not been tested against a brand new instance.
ssh -i "$pem_file" "$EC2_INSTANCE" << 'ENDSSH'
yum install docker
sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

# This is setup for init-letsencrypt.sh
mkdir -p ~/data/nginx
ENDSSH

scp -i "$pem_file" "$IC_ROOT/build/credentials/prod.env" "$EC2_INSTANCE:~/prod.env"
scp -i "$pem_file" "$IC_ROOT/config/docker/compose.yml" "$EC2_INSTANCE:~/compose.yml"
scp -i "$pem_file" "$IC_ROOT/config/docker/nginx/app.conf" "$EC2_INSTANCE:~/nginx/app.conf"
scp -i "$pem_file" "$IC_ROOT/config/docker/init-letsencrypt.sh" "$EC2_INSTANCE:~/init-letsencrypt.sh"

ssh -i "$pem_file" "$EC2_INSTANCE" << 'ENDSSH'
chmod +x ~/init_letsencrypt.sh
~/init-letsencrypt.sh
ENDSSH

