#!/usr/bin/env bash
set -euo pipefail
. "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"
ensure_credentials_exist

. "$IC_ROOT/build/credentials/runner.sh"

ssh -i "$pem_file" "$EC2_INSTANCE" << 'ENDSSH'
sudo docker logs production &> test.log
ENDSSH

logs_dir="$IC_BUILD/production_logs"
filename="$(date +'%d-%b-%Y')-icompass-prod.log"
mkdir -p "$logs_dir"
echo "saving logs to $logs_dir/$filename"
scp -i "$pem_file" "$EC2_INSTANCE:/home/ubuntu/test.log" "$logs_dir/$filename"
