#!/usr/bin/env bash
set -euo pipefail
. "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"

WEBPACK=0
SPEC_FILE=*
HEADLESS=1

while [[ $# -gt 0 ]]; do
    case "$1" in
        --with-webpack|-w)
            WEBPACK=1
            ;;

        --only|-o)
            SPEC_FILE="$2"
            if [[ ! -e "$IC_ROOT/test/e2e/$SPEC_FILE.spec.js" ]]; then
                echo "The specified test file test/e2e/$SPEC_FILE.spec.js does not exist" >&2
                exit 1
            else
                echo ""
                echo "Running only: $SPEC_FILE.spec.js"
                echo ""
            fi
            ;;

        --headed|-h)
            echo "Headless mode turned off"
            HEADLESS=0
            ;;


        -*)
            echo "unknown option $1." >&2
            exit 1
            ;;
    esac
    shift
done

if [[ "$WEBPACK" -eq 1 ]]; then
    echo "running webpack..." >&2
    "$IC_ROOT/scripts/build-webpack"
fi

echo "Waiting for server to start"
i="0"
until $(curl --output /dev/null --silent --head --fail "http://localhost:8080"); do
    if [[ "$i" -gt 30 ]]; then
        echo "iCompass server not detected. Exiting"
        exit 1
    fi
    printf '.'
    i=$[$i+1]
    sleep 1
done
echo "iCompass server detected"

echo "clearing errorShots/ folder"
if [[ -d "$IC_ROOT/errorShots" ]]; then
    rm -r "$IC_ROOT/errorShots/"
fi

echo ""
echo "running webdriverio tests..."
SPECS="$SPEC_FILE" HEADLESS="$HEADLESS" "$IC_ROOT/node_modules/.bin/wdio" "$IC_ROOT/config/wdio/local.js"
