---
resources:
- name: icompass
  type: git
  source:
    uri: https://github.com/thecardkid/icompass.git
    branch: develop

jobs:
- name: tests
  serial: true
  plan:
  - aggregate:
    - get: icompass
      trigger: true
  - task: mocha
    file: icompass/ci/test/test.yml
