---
resources:
- name: icompass
  type: git
  source:
    uri: https://github.com/thecardkid/icompass.git
    branch: ci

jobs:
- name: mocha
  serial: true
  plan:
  - get: icompass
    trigger: true
  - task: mocha
    file: icompass/ci/mocha/mocha.yml
- name: e2e
  serial: true
  plan:
  - get: icompass
    trigger: true
  - task: e2e
    file: icompass/ci/e2e/e2e.yml
