on: push
jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.15.3'
    - uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: '4.2.6'
    - run: npm install --depth 0
    - run: npm run lint
    - run: npm run api
